### PR TITLE
Add another over example, mention DE-9IM

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by edzer** [comment]
I agree that this part needs improvement, in particular for the case where a point is on a polygon edge or two polygon touch. Both cases result in positive `over` hits, but your text ("overlay", "overlapping edges") does IMO not make this explicit enough. I propose to modify the toy data set such that it includes "touch" cases (point on edge, touching polygons), and the text should emphasize that.

**Comment by Robinlovelace** [comment]
Agreed. I will add a 'touches' example - PRs are a great forum for discussion before the changes are accepted. Thanks for the feedback.

**Comment by edzer** [comment]
Hang on.

**Comment by edzer** [comment]
some clarification here: https://github.com/edzer/sp/commit/e0e15742c745e7f059ebb16a22fffa2f0a89f039

**Comment by Robinlovelace** [comment]
Aha, great stuff. Shall I add new prose for that updated example then?

**Comment by edzer** [comment]
If you see room for improvement: Yes.

**Pull request merged**
