### PR TITLE
-Wstrict-prototypes warnings

### PR DESCRIPTION
**Pull request by rsbivand**
Only https://github.com/edzer/sp/commit/b351d7bf1b84e231ea75df24626e64c61c6632d6 relevant now to resolve https://cran.r-project.org/web/checks/check_results_rgeos.html and https://cran.r-project.org/web/checks/check_results_sp.html (and partly https://cran.r-project.org/web/checks/check_results_rgdal.html).

### CODE REVIEW

**Comment by edzer** [comment]
Shall I merge everything or only the missing `void` decls?

**Comment by rsbivand** [comment]
Please wait, I'm checking on an instrumented platform, and there is also an unconditional use of spTransform. I'll let you know when I'm ready. Reviewing the existing pile of commits is needed too.

**Comment by rsbivand** [comment]
OK, I think this is OK now, `-Wstrict-prototypes` fixed and also checks in status `0L` with no retiring packages present. `aggregate()`, `disagregate()` and `over()`  need attention for status `2L` and **sf** instead of **rgeos**, for the next release. Going with this now (with vignette compaction "both") should be OK.

**Comment by rsbivand** [comment]
Should I check on the instrumented system?

**Comment by rsbivand** [comment]
[00check.log](https://github.com/edzer/sp/files/9935927/00check.log

[00install.zip](https://github.com/edzer/sp/files/9935937/00install.zip)

```
$ R CMD build --compact-vignettes="both" sp
_SP_EVOLUTION_STATUS_=2 _R_CHECK_FORCE_SUGGESTS_=FALSE R_LIBS=/home/rsb/topics/R/devel-libs PATH=/home/rsb/topics/R/trunk/build/bin:$PATH R CMD check sp_1.5-1.tar.gz
```
(On train, no signal in tunnels)

**Comment by edzer** [comment]
Thanks, submitted to CRAN.

**Comment by rsbivand** [comment]
And check on submitted rgdal:
[00check.log](https://github.com/edzer/sp/files/9936016/00check.log)

and trunk status rgeos:

[00check.log](https://github.com/edzer/sp/files/9936040/00check.log)

**Pull request merged**
